apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdwej
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdwej
  template:
    metadata:
      labels:
        app: sdwej
    spec:
      containers:
      - image: okteto.dev/sdwej:latest
        name: sdwej
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "06d56ee6-af9c-4219-82ba-6baf287fd524"
        - name: Vless_Path
          value: "/vl5dfrt5"
        - name: Vmess_UUID
          value: "06d56ee6-af9c-4219-82ba-6baf287fd524"
        - name: Vmess_Path
          value: "/vmsdet6"
        - name: Share_Path
          value: "/v2link"
