apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiorbmpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iiorbmpe
  template:
    metadata:
      labels:
        app: iiorbmpe
    spec:
      containers:
      - image: okteto.dev/iiorbmpe:latest
        name: iiorbmpe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "027bfddd-fa85-4167-a848-a198e7497ca5"
        - name: Vless_Path
          value: "/vl5dfrt5"
        - name: Vmess_UUID
          value: "027bfddd-fa85-4167-a848-a198e7497ca5"
        - name: Vmess_Path
          value: "/vmsdet6"
        - name: Share_Path
          value: "/v2link"
